In [1]:
# graficos embebidos
%matplotlib inline

In [51]:
# importando pandas, numpy y matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import sklearn.metrics
import itertools

# importando los datasets de sklearn
from sklearn import datasets



In [52]:
#Abrimos archivos
df = pd.read_csv("juegos.csv")
df.head()

Unnamed: 0  index  Rank                      Name Platform Platform2  \
0           0      0   1.0                Wii Sports      Wii       Wii   
1           1      1   2.0         Super Mario Bros.      NES      OTRA   
2           2      2   3.0            Mario Kart Wii      Wii       Wii   
3           3      3   4.0         Wii Sports Resort      Wii       Wii   
4           4      4   5.0  Pokemon Red/Pokemon Blue       GB      OTRA   

     Year  Year2         Genre Publisher  NA_Sales  EU_Sales  JP_Sales  \
0  2006.0   2006        Sports  Nintendo     41.49     29.02      3.77   
1  1985.0   1993      Platform  Nintendo     29.08      3.58      6.81   
2  2008.0   2008        Racing  Nintendo     15.85     12.88      3.79   
3  2009.0   2009        Sports  Nintendo     15.75     11.01      3.28   
4  1996.0   1996  Role-Playing  Nintendo     11.27      8.89     10.22   

   Other_Sales  Global_Sales  Genero  Plataforma  
0         8.46         82.74       0        15.0  
1         0.77         40.24       1        20.0  
2         3.31         35.82       7        15.0  
3         2.96         33.00       0        15.0  
4         1.00         31.37      11        20.0

In [53]:
##Cargar variables excluyendo las que no se ocupan 
X = np.array(df.drop(['Name','Platform','Platform2','Year','Genre',
                             'Publisher','NA_Sales','EU_Sales','JP_Sales','Other_Sales','index','Unnamed: 0','Rank'],1))
y = np.array(df['Genero'])
X.shape

(16594, 4)

In [54]:
# importando el modelo de regresión lineal
from sklearn.linear_model import LinearRegression

rl = LinearRegression() # Creando el modelo.
rl.fit(X,y ) # ajustando el model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [55]:
# Lista de coeficientes B para cada X
list(zip(X, rl.coef_))

[(array([ 2006.  ,    82.74,     0.  ,    15.  ]), 4.8486003097183968e-18),
 (array([  1.99300000e+03,   4.02400000e+01,   1.00000000e+00,
           2.00000000e+01]), -5.5511151231257827e-17),
 (array([ 2008.  ,    35.82,     7.  ,    15.  ]), 1.0),
 (array([ 2009.,    33.,     0.,    15.]), 0.0)]

In [56]:
# haciendo las predicciones
predicciones = rl.predict(X)
predicciones_df = pd.DataFrame(predicciones, columns=['Prediccion'])
predicciones_df.head() # predicciones de las primeras 5 lineas

Prediccion
0 -4.636663e-15
1  1.000000e+00
2  7.000000e+00
3 -1.860993e-15
4  1.100000e+01

In [48]:
# Calculando el desvio
np.mean(y - predicciones)

8.9152194802501144e-17